---
all:
  hosts:
    adap-server:
      ansible_port: 22

    sumaris-server:
      ansible_port: 2200

    sfa-test-server-debian:
      ansible_port: 22

    sfa-test-server-debian9:
      ansible_port: 22

    sfa-test-server-ubuntu:
      ansible_port: 22

production:
  hosts:
    adap-server:

test:
  hosts:
    #adap-server:
    sumaris-server:
    sfa-test-server-debian:
    sfa-test-server-debian9:
    sfa-test-server-ubuntu: