username: test
sumaris_host: '{{ username }}.{{ hostvars[inventory_hostname].default_domain }}'

pod_salt: '{{ username }}@{{ sumaris_host }}'
pod_password: '{{ username }}'
pod_address: '127.0.0.1'
pod_port: 8081
pod_jvm_opts: '-Xms2g -Xmx2g'

# Pod features config
pod_rdf_enabled: false
pod_denormalized_batch: false

db_type: 'hsqldb'
db_host: '127.0.0.1'
db_port: 9002
db_name: 'sumaris-{{ username }}'
db_reset: false
db_username: 'sa'
db_password: ''
db_backup_ftp_url: ''
db_backup_ftp_dir: '/sumaris-db-{{ username }}-backup/'
db_backup: true
db_jvm_opts: '-Xms512m -Xmx1024m'

# Use HsqlDB v2.4.1 by default, because error on 2.5, on "grouping" table (becomes a reserved word)
db_hsqldb_version: '{{ db_hsqldb.default.version }}'
db_hsqldb_hash_file: '{{ db_hsqldb.default.hash_file }}'
db_hsqldb_tool_hash_file: '{{ db_hsqldb.default.tool_hash_file }}'

app_name: SUMARiS
app_default_peer: true
app_base_path: ''

apk_dir: '/opt/{{ username }}/{{ target_dir }}/data/download/android'
apk_latest_basename: 'sumaris-app-latest.apk'
apk_install_url: 'https://{{ sumaris_host }}{{ app_base_path }}/download/android/{{ apk_latest_basename }}'

# Other vars
admin_email: contact@e-is.pro
target_dir: sumaris-pod

nginx_default_server: false
ssl_only: True
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail.smtp:
        auth: true
        starttls:
          enable: true
          required: true