# Pod version
pod_version: 0.20.2
jar_file: 'https://github.com/sumaris-net/sumaris-pod/releases/download/v{{ pod_version }}/sumaris-pod-{{ pod_version }}.jar'
jar_hash_file: sha256:075793ab47ed28c4f8f7e13e6f9c1f71e19c161f9407de23d0efecf21f4bba39
pod_jvm_opts: '-Xms512m -Xmx1024m -Duser.timezone=UTC'

# DB data version
db_version: 0.20.2
db_file: 'https://github.com/sumaris-net/sumaris-pod/releases/download/v{{ db_version }}/sumaris-db-{{ db_version }}.zip'
db_hash_file: sha256:ce5508c9d19e5a5d8e20766d2c35c754831f78ddf4c52f6f1a23a81836bcb55f
db_jvm_opts: '-Xms512m -Xmx1024m'

# DBMS version
db_hsqldb_version: 2.4.1
db_hsqldb_file: 'http://www.hsqldb.org/repos/org/hsqldb/hsqldb/{{ db_hsqldb_version }}/hsqldb-{{ db_hsqldb_version }}.jar'
db_hsqldb_hash_file: sha256:417294fff9d6b6a4f7ee522982ed2693cdda28d131da0d9e4f048a57d6e1cdb2
db_hsqldb_tool_file: 'http://www.hsqldb.org/repos/org/hsqldb/sqltool/{{ db_hsqldb_version }}/sqltool-{{ db_hsqldb_version }}.jar'
db_hsqldb_tool_hash_file: sha256:a03fb31971064fe66655ce0ebe0902fca5e9d2cbe7295f953e29e79e8a77843c

# App web version
app_version: 0.20.1
app_file: 'https://github.com/sumaris-net/sumaris-app/releases/download/v{{ app_version }}/sumaris-app-v{{ app_version }}-web.zip'
app_hash_file: sha256:7abd73fb488b3e66e7f5b68baef8d0f00b00f5f9fdf77e874e4a84db65621613

# App Android version
apk_version: 0.20.1
apk_file: 'https://github.com/sumaris-net/sumaris-app/releases/download/v{{ apk_version }}/sumaris-app-v{{ apk_version }}-android.apk'
apk_hash_file: sha256:2d9b7b11c3b33cd8aec0fc4fd08c82c089bff495b5c0ee6a8af5a34e2e8d3a92

# Other vars
admin_email: contact@e-is.pro
target_dir: sumaris-pod
