# Pod version
pod_version: 1.4.6
jar_file: 'https://github.com/sumaris-net/sumaris-pod/releases/download/{{ pod_version }}/sumaris-pod-{{ pod_version }}.war'
jar_hash_file: sha256:c9dfea65a620b5365dd890ed27f701932baeefab196b06962efd8ed4e49479a6
pod_jvm_opts: '-Xms512m -Xmx1024m'

# DB data version
db_version: 1.4.6
db_file: 'https://github.com/sumaris-net/sumaris-pod/releases/download/{{ db_version }}/sumaris-db-{{ db_version }}.zip'
db_hash_file: sha256:243ec119c0ec7f73c37fa4e93d344b620cae58c41aee850db141e42e00f4559f
db_jvm_opts: '-Xms512m -Xmx1024m'

# DBMS version
db_hsqldb_version: 2.5.0
db_hsqldb_file: 'http://www.hsqldb.org/repos/org/hsqldb/hsqldb/{{ db_hsqldb_version }}/hsqldb-{{ db_hsqldb_version }}.jar'
db_hsqldb_hash_file: sha256:acda459cc9d6a07b39b284364e93b5f29e11877d687e9544b91778d3554d2b38
db_hsqldb_tool_file: 'http://www.hsqldb.org/repos/org/hsqldb/sqltool/{{ db_hsqldb_version }}/sqltool-{{ db_hsqldb_version }}.jar'
db_hsqldb_tool_hash_file: sha256:e8945946e87a2b66058719deb7a9a9722b6a6b71f151a45eb52e3b12a4663b67

# App web version
app_version: 1.4.6
app_file: 'https://github.com/sumaris-net/sumaris-app/releases/download/{{ app_version }}/sumaris-app-{{ app_version }}-web.zip'
app_hash_file: sha256:9988cb4b1fb5ff7c5843a0fd73bc403796cfc1d135335822b3669eddcf223520

# App Android version
apk_version: 1.4.6
apk_basename: 'sumaris-app-{{ apk_version }}-android.apk'
apk_file: 'https://github.com/sumaris-net/sumaris-app/releases/download/{{ apk_version }}/{{ apk_basename }}'
apk_hash_file: sha256:9988cb4b1fb5ff7c5843a0fd73bc403796cfc1d135335822b3669eddcf223520

# Other vars
admin_email: contact@e-is.pro
target_dir: sumaris-pod
