
- name: Pod {{ username }} - Requirements
  include_tasks: requirements.yml

- name: Pod {{ username }} - Configure Database
  include_tasks: db_hsqldb.yml
  when: db_type == 'hsqldb'

- name: Pod {{ username }} - Configure Pod
  include_tasks: pod.yml

- name: Pod {{ username }} - Configure App web site
  include_tasks: app.yml

- name: Pod {{ username }} - Configure script bin/sumaris-status.sh
  template:
    src: templates/bin/sumaris-status.sh.j2
    dest: /opt/{{ username }}/{{target_dir}}/bin/sumaris-status.sh
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0755