- name: Check if SELinux is running
  command: getenforce
  register: sestatus
  changed_when: false

- name: Configure SELinux on CentOS
  seport:
    ports: 2200 
    proto: tcp
    setype: ssh_port_t
    state: present
  when: '"Enforcing" in sestatus.stdout'

- name: Stop and disable firewalld
  systemd:
    enabled: no
    state: stopped
    name: firewalld
