
- name: Install fail2ban and iptables
  apt: 
    pkg: [fail2ban,  iptables-persistent]
    state: latest

#- name: Enable iptables-services
#  systemd:
#    enabled: yes
#    state: started
#    name: iptables
#
#- name: Enable fail2ban
#  systemd:
#    enabled: yes
#    state: started
#    name: fail2ban
