
- name: Authorize INPUT local connexions (ipv4)
  iptables:
    ip_version: ipv4
    chain: INPUT
    protocol: tcp
    destination: localhost
    jump: ACCEPT

- name: Authorize INPUT local connexions (ipv4)
  iptables:
    ip_version: ipv4
    chain: INPUT
    protocol: tcp
    destination: 127.0.0.1
    jump: ACCEPT

- name: Get existing iptables rules
  become: true
  command: iptables -n -L
  changed_when: false
  register: iptables_rules

- name: Create f2b-sshd iptables chain
  become: true
  command: iptables -N 'f2b-sshd'
  when: "'Chain f2b-sshd' not in iptables_rules.stdout"

- name: Configure chain f2b-sshd
  iptables:
    chain: f2b-sshd
    protocol: all
    jump: RETURN

- name: Filter ansible port with fail2ban (ipv4)
  iptables:
    ip_version: ipv4
    chain: INPUT
    protocol: tcp
    destination_port: "{{ ansible_port }}"
    jump: f2b-sshd

- name: Authorize ansible port from ssh jump
  include_tasks: iptables_ssh_jump.yml
  loop: "{{ managing_hosts }}"
  when: managing_hosts[0] != 'localhost'

- name: Authorize ansible port from world wide web
  include_tasks: iptables_ssh_any.yml
  when: managing_hosts[0] == 'localhost'

- name: Allow related and established connections
  iptables:
    ip_version: ipv4
    chain: INPUT
    ctstate: "{{ iptables_ctstate }}"
    jump: ACCEPT

- name: Allow related and established connections
  iptables:
    ip_version: ipv6
    chain: INPUT
    ctstate: ESTABLISHED,RELATED,NEW
    jump: ACCEPT

- name: Set the policy for the INPUT chain to DROP (ipv4)
  iptables:
    ip_version: ipv4
    chain: INPUT
    policy: DROP

- name: Set the policy for the INPUT chain to DROP (ipv6)
  iptables:
    ip_version: ipv6
    chain: INPUT
    policy: DROP

- name: Authorize OUTPUT TCP connexions (ipv4)
  iptables:
    ip_version: ipv4
    chain: OUTPUT
    protocol: tcp
    jump: ACCEPT

- name: Authorize OUTPUT TCP connexions (ipv6)
  iptables:
    ip_version: ipv6
    chain: OUTPUT
    protocol: tcp
    jump: ACCEPT

- name: Save the rules ipv4
  shell: iptables-save > /etc/iptables/rules.v4
  
- name: Save the rules ipv6
  shell: ip6tables-save > /etc/iptables/rules.v6
