
- name: Configure ssh port
  include_tasks: set_ssh_port.yml
  when: managing_hosts[0] != 'localhost'

# Gather facts should be set to false when running this role since it will
# fail if the Ansible SSH port is not set correctly.
# We run setup to gather facts here once the SSH port is set up.
- name: Run deferred setup to gather facts
  setup:

- name: Set hostname
  hostname: 
    name: "{{ inventory_hostname }}"
    
- name: Set hosts file
  lineinfile:
    dest: "/etc/hosts"
    line: "127.0.0.1 {{ inventory_hostname }}"
    state: present

- name: Set resolv.conf file
  lineinfile:
    dest: "/etc/resolv.conf"
    line: "nameserver {{ item }}"
    state: present
  with_items: "{{ nameservers }}"
  when: nameservers is defined

- name: Configure /etc files
  include_tasks: etc.yml    

- name: Download and configure packages on CentOS
  include_tasks: centos_packages.yml    
  when: ansible_distribution == "CentOS"

- name: Download and configure packages on Debian
  include_tasks: debian_packages.yml    
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

# For distribution Debian <=9
- name: Configure jail
  include_tasks: jail.yml
#  when: ansible_distribution == "Debian" and ansible_distribution_major_version < 10

- name: Configure iptables
  include_tasks: iptables.yml
#  when: ansible_distribution == "Debian" and ansible_distribution_major_version < 10

# For distribution Debian = 10
#- name: Configure fail2ban
#  include_role:
#    name: fail2ban
#  vars:
#    fail2ban_services:
#      - name: sshd
#        port: "{{ ansible_port }}"
#        bantime: 3600
#  when: ansible_distribution == "Debian" and ansible_distribution_major_version == 10

- name: Configure admins
  include_tasks: admins.yml
  loop: "{{ admins | dict2items }}"
