hostname: adap.pecheursdebretagne.eu
trigramme: ADP
default_domain: adap.pecheursdebretagne.eu # default nginx domain
nginx_default_server: False
local_name: adap.pecheursdebretagne.local

# DB backup:
db_backup_ftp_url: ftp://eisvskrx-adap:Adap2019@ftp.cluster014.hosting.ovh.net

nameservers:
 - 95.128.151.231
 - 95.128.151.232

# SMTP config
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: sumaris.net@gmail.com
    password: yohwtdrskzknmqah
    properties:
     mail:
      smtp:
       auth: true
       starttls:
        enable: true
        required: true